---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-vcluster-flappy-kray
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    kubefirst.konstruct.io/application-name: flappy-kray
    kubefirst.konstruct.io/source: catalog-templates
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: flappy-kray
    name: dev-vcluster
  source:
    repoURL: 'https://charts.kubefirst.com'
    targetRevision: 0.1.0
    chart: flappy-kray
    helm:
      values: |
        image:
          repository: ghcr.io/konstructio/flappy-kray

        ingress:
          enabled: true
          className: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            argocd.argoproj.io/sync-wave: '1'
          hosts:
            - host: flappy-kray.azure-demo.kubefirst.simonemms.com
              paths:
                - path: /
                  pathType: Prefix
          tls:
          - secretName: flappy-kray-tls
            hosts:
              - flappy-kray.azure-demo.kubefirst.simonemms.com
  project: dev-vcluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
