apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-environment-metaphor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '45'
spec:
  project: default
  source:
    repoURL: git@github.com:mrsimonemmsorg2/gitops.git
    path: registry/environments/staging/metaphor
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
