apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubefirst
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://charts.konstruct.io
    targetRevision: 2.7.5-rc13
    chart: kubefirst-pro
    helm:
      values: |-
        global:
          cloudProvider: "azure"
          clusterId: "scbgzt"
          clusterType: "mgmt"
          domainName: "azure-demo.kubefirst.simonemms.com"
          gitProvider: "github"
          installMethod: "helm"
          kubefirstClient: "<KUBEFIRST_CLIENT>"
          kubefirstTeam: "true"
          kubefirstTeamInfo: ""
          kubefirstVersion: "main"
          useTelemetry: ""
        kubefirst-pro-api:
          extraEnv:
            CLUSTER_NAME: "sje-azure-demo"
        kubefirst-pro-ui:
          domain: "azure-demo.kubefirst.simonemms.com"
          extraEnvSecrets:
            CLIENT_ID:
              name: kubefirst-console-secrets
              key: client_id
            SECRET_ID:
              name: kubefirst-console-secrets
              key: client_secret
          ingress:
            enabled: "true"
            className: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              
              
              
            hosts:
              - host: kubefirst.azure-demo.kubefirst.simonemms.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: kubefirst-tls
                hosts:
                  - kubefirst.azure-demo.kubefirst.simonemms.com
  destination:
    name: in-cluster
    namespace: kubefirst
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
