apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '50'
spec:
  project: default
  source:
    repoURL: git@github.com:mrsimonemmsorg2/gitops.git
    path: registry/clusters/sje-azure-demo/components/argo-workflows
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
