apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-vcluster-provider-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: git@github.com:mrsimonemmsorg2/gitops.git
    path: registry/clusters/dev-vcluster/provider-config
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
