apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-vcluster-ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '30'
spec:
  project: dev-vcluster
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |-
        controller:
          podAnnotations:
            linkerd.io/inject: enabled
          ingressClass: nginx
          publishService:
            enabled: true
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
            externalTrafficPolicy: Local
          extraArgs:
            enable-ssl-passthrough: true
    chart: ingress-nginx
  destination:
    name: dev-vcluster
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
